name: Lint and Build

on:
  - pull_request
  - push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get App's cache
        uses: actions/cache@v2
        id: app_cache
        with:
          path: |
            ~/.npm
            ./node_modules

          key: ${{ runner.os }}-app1-${{ hashFiles('package-lock.json') }}

      - name: show cache status
        run: |
          echo ${{steps.app_cache.outputs.cache-hit}}

      - name: Get Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Use npm version 7
        run: |
          npm install -g npm@7

      - name: Install rc-apps CLI
        run: |
          npm install -g @rocket.chat/apps-cli
          rc-apps -v

      - name: check install location
        run: |
          npm root -g

      - name: Install dependencies
        run: npm ci
        if: steps.app_cache.outputs.cache-hit != 'true'

      - name: Cache all of the above for next steps
        uses: actions/cache@v2
        id: cache_app_actions
        with:
          path: |
            ./*
            /usr/local/lib/node_modules
          key: app_actions-${{github.sha}}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: restore cache
        uses: actions/cache@v2
        id: restore_app_actions_cache
        with:
          path: ./*
          key: app_actions-${{github.sha}}

      - name: check lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: restore cache
        uses: actions/cache@v2
        id: restore_app_actions_cache
        with:
          path: |
            ./*
            /usr/local/lib/node_modules
          key: app_actions-${{github.sha}}
      - name: package as Rocket.Chat app
        run: rc-apps package
